DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Controllers/KhaiBaoAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DACSN.Models;
using System.IO;
using PagedList;
using System.Data.Entity;

namespace DACSN.Areas.Admin.Controllers
{
    public class KhaiBaoAdminController : Controller
    {
        dbDuLieuYTeBDDataContext data = new dbDuLieuYTeBDDataContext();

        // GET: Admin/KhaiBaoYTe
        public ActionResult KhaiBaoYTe(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 30;
            var kq = data.ThongTin_KhaiBaos.ToList().OrderByDescending(n => n.NgayKhaiBao);
            ViewBag.TongSoLuong = kq.Count();
            return View(kq.ToPagedList(iPageNum, iPageSize));
           

        }
        //public ActionResult SL_KhaiBao()
        //{
        //    return PartialView();
        //}
        public ActionResult SearchSl_KhaiBao(string strSearch,string searchstring  ,int? page, int IdDistrict=0  )
        {
           
            int iPageNum = (page ?? 1);
            int iPageSize = 30;
            var dl = data.ThongTin_KhaiBaos.Include(b => b.Province).Include(b => b.District);
            ViewBag.Search = searchstring;
            
            if (!String.IsNullOrEmpty(searchstring))
                {
                var kq = from s in data.ThongTin_KhaiBaos where s.TinhTrang.Contains(searchstring)  select s;
                ViewBag.Count = kq.Count();

                //var kq = from s in data.ThongTin_KhaiBaos where s.NgayKhaiBao.ToString().Contains(strSearch)   select s ;
                return View(kq.ToPagedList(iPageNum, iPageSize));
            }

            //else if (String.IsNullOrEmpty(searchstring) && !String.IsNullOrEmpty(strSearch))
            //{
            //    var kq = from s in data.ThongTin_KhaiBaos where s.HoVaTen.Contains(strSearch) select s;
            //    return View(kq.ToPagedList(iPageNum, iPageSize));
            //}
            //    if(IdDistrict != 0)
            //{
            //    dl = dl.Where(c => c.QuanHuyen == IdDistrict);
            //}
            //ViewBag.IdDistrict = new SelectList(data.Districts, "Id", "Name"); // danh sách Category               
            return View(dl.ToList().ToPagedList(iPageNum, iPageSize));
            
            
           
        }
        public ActionResult ThongKe()
        {
            
           
            return View();
        }

        public ActionResult ThongKe_BinhDuong()
        {
            ViewBag.TDM   = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen==718   select s).Count();
            ViewBag.DT = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen == 720 select s).Count();
            ViewBag.BC = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen == 721 select s).Count();
            ViewBag.PG = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen == 722 select s).Count();
            ViewBag.TU = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen == 723 select s).Count();
            ViewBag.DA = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen == 724 select s).Count();
            ViewBag.TA = (from s in data.ThongTin_KhaiBaos where s.QuanHuyen == 725 select s).Count();
            //74
            return PartialView();
        }
        public ActionResult ThongKe_BinhDuong_2()
        {
            ViewBag.Tiepxuc = (from s in data.ThongTin_KhaiBaos where s.TiepXucCOVID.ToString().Contains("true") select s).Count();
            ViewBag.Vungdich = (from s in data.ThongTin_KhaiBaos where s.NguoiVungCovid.ToString().Contains("true") select s).Count();
            ViewBag.Trieuchung = (from s in data.ThongTin_KhaiBaos where s.NguoiSotHo.ToString().Contains("true") select s).Count();
            ViewBag.TinhTrang = (from s in data.ThongTin_KhaiBaos where s.TinhTrang.Contains("dấu hiệu bất thường") select s).Count();
            //var taisan = from s in data.ThongTin_KhaiBaos
            //             from x in data.Districts
            //             //from y in _db.DONVITAISANs
            //             //from z in _db.DONVIs
            //             where s.QuanHuyen== x.Id
            //             //where y.MaTS == s.MaTS
            //             //where z.MaDV == y.MaDV
            //             select new
            //             {
            //                 //TenTS = s.TenTS,
            //                 SoLuong = s.d.FirstOrDefault().Soluong,
            //                 //TenDV = (s.DONVITAISANs.FirstOrDefault()).DONVI.TenDV,
            //                 //SoLuongDV = s.DONVITAISANs.FirstOrDefault().Soluong,
            //                 //ConLai = (s.GIATRITAISANs.FirstOrDefault().Soluong - s.DONVITAISANs.FirstOrDefault().Soluong)

            //             };

            return PartialView();
        }

        public ActionResult thongke_TiepXuc(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 30;
            var Tiepxuc = from s in data.ThongTin_KhaiBaos where s.TiepXucCOVID.ToString().Contains("true") select s;
            return PartialView(Tiepxuc.ToList().ToPagedList(iPageNum, iPageSize));
        }
        public ActionResult thongke_Vungdich(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 30;
            var Tiepxuc = from s in data.ThongTin_KhaiBaos where s.NguoiVungCovid.ToString().Contains("true") select s;
            return PartialView(Tiepxuc.ToList().ToPagedList(iPageNum, iPageSize));
        }
        public ActionResult thongke_Trieuchung(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 30;
            var Tiepxuc = from s in data.ThongTin_KhaiBaos where s.NguoiSotHo.ToString().Contains("true") select s;
            return PartialView(Tiepxuc.ToList().ToPagedList(iPageNum, iPageSize));
        }
    }
}

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/KhaiBaoAdmin/KhaiBaoYTe.cshtml
@using DACSN.Models
@using PagedList.Mvc;
@model PagedList.PagedList<DACSN.Models.ThongTin_KhaiBao>

@{
    ViewBag.Title = "KhaiBaoYTe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Khai Báo Y Tế</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@
<div class="form-group">
    <label style="font-size:larger">Số lượng khai báo  :</label> @ViewBag.TongSoLuong
</div>
@using (Html.BeginForm("SearchSl_KhaiBao", "KhaiBaoAdmin", FormMethod.Get, new { @class = "navbar-form navbar-right", @role = "search" }))
{

    <label>Tình trạng</label>
    <input type="text" class="form-control" name="searchstring" value="@ViewBag.Search" />
    <button type="submit" class="btn btn-danger">Tìm</button>
}
@*<label>Quận Huyện:</label>@Html.DropDownList("Id", null, htmlAttributes: new { @class = "form-control" }) <label>Tình trạng: </label>*@
<table class="table">
    <tr>
        <th>
            Họ và Tên
        </th>
        <th>
            CMND / CCCD
        </th>
        <th>
            Năm sinh
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuocTich)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().PhuongXa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuanHuyen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhThanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhTrang)
            @*</th>
                <th>
                    @Html.DisplayNameFor(model => model.First().TiepXucCOVID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().NguoiVungCovid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().NguoiSotHo)
                </th>*@
        <th>
            @Html.DisplayNameFor(model => model.First().NgayKhaiBao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoVaTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.FormatValue(item.NamSinh, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuocTich)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ward.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Province.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.TiepXucCOVID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiVungCovid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiSotHo)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.NgayKhaiBao)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.ID })
                </td>*@
        </tr>
    }

</table>
<!-- Thêm mã phân trang -->
        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
        <div class="MenuTrang">

            @Html.PagedListPager(Model, page => Url.Action("KhaiBaoYTe", new { page = page }))
        </div>
        <style>
            .MenuTrang {
                display: inline;
                text-align: center;
            }
        </style>

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/KhaiBaoAdmin/SearchSl_KhaiBao.cshtml
@using DACSN.Models
@using PagedList.Mvc;
@model PagedList.PagedList<DACSN.Models.ThongTin_KhaiBao>
@{
    ViewBag.Title = "SearchSl_KhaiBao";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Kết quả tìm được</h2>
<div class="form-group">
    <label style="font-size:larger">Số lượng :</label> @ViewBag.Count
</div>
<table class="table">
    <tr>
        <th>
            Họ và Tên
        </th>
        <th>
            CMND / CCCD
        </th>
        <th>
            Năm sinh
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuocTich)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().PhuongXa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuanHuyen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhThanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhTrang)
            @*</th>
                <th>
                    @Html.DisplayNameFor(model => model.First().TiepXucCOVID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().NguoiVungCovid)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().NguoiSotHo)
                </th>*@
        <th>
            @Html.DisplayNameFor(model => model.First().NgayKhaiBao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoVaTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.FormatValue(item.NamSinh, "{0:dd/MM/yyyy}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuocTich)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ward.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Province.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.TiepXucCOVID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiVungCovid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiSotHo)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.NgayKhaiBao)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                    @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.ID })
                </td>*@
        </tr>
    }

</table>
<!-- Thêm mã phân trang -->
Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
<div class="MenuTrang">

    @Html.PagedListPager(Model, page => Url.Action("SearchSl_KhaiBao", new { page = page }))
</div>
<style>
    .MenuTrang {
        display: inline;
        text-align: center;
    }
</style>
@Html.ActionLink("Quay lại Trang", "KhaiBaoYTe", "KhaiBaoAdmin")

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/KhaiBaoAdmin/ThongKe.cshtml
@{
    ViewBag.Title = "ThongKe";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<h2 style="text-align:center">Thống kê Y Tế Tỉnh Bình Dương</h2>

    <div class="row">
        <div class="col-lg-12 well">
            @Html.Action("ThongKe_BinhDuong", "KhaiBaoAdmin")
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 well">
            @Html.Action("ThongKe_BinhDuong_2", "KhaiBaoAdmin")
        </div>
    </div>

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/KhaiBaoAdmin/ThongKe_BinhDuong_2.cshtml
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>

<figure class="highcharts-figure">
    <div id="container"></div>
    <p class="highcharts-description">
       
    </p>
</figure>
<script>
    Highcharts.chart('container', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Số lượng người Tình nghi F0,F1'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
           
        },
        accessibility: {
            point: {
                valueSuffix: '%'
            }
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Tiếp xúc',
            colorByPoint: true,
            data: [{
                name: 'Người bị Covid 19',
                y: @ViewBag.Tiepxuc,
                sliced: true,
                selected: true
            }, {
                name: 'Người từ Vùng dịch',
                y: @ViewBag.Vungdich
            }, {
                name: 'Người có biểu hiện (sốt ,ho , khó thở)',
                y:  @ViewBag.Trieuchung
            }
            ]
        }]
       
    });
</script>

<p>
    TIẾP XÚC VỚI NHỮNG TRƯỜNG HỢP SAU:
</p>
<table class="table">

    <tr>
        <th></th>
        <th>
            Người bị Covid 19
        </th>
        <th>
            Người từ Vùng dịch
        </th>
        <th>
            Người có biểu hiện (sốt ,ho , khó thở)
        </th>
        <th>
            Có triệu chứng sau khi tiếp xúc
        </th>
        <th></th>
    </tr>


    <tr>
        <th>Số lượng người tiếp xúc :</th>
        <td>
            @ViewBag.Tiepxuc
        </td>
        <td>
            @ViewBag.Vungdich
        </td>
        <td>
            @ViewBag.Trieuchung
        </td>
        <td>
            @ViewBag.TinhTrang
        </td>
        <td>
            @ViewBag.SL_KhaiBao
        </td>

    </tr>
    <tr>
        <td></td>
        <td>@Html.ActionLink("Details","thongke_TiepXuc", "KhaiBaoAdmin") </td>
        <td>@Html.ActionLink("Details", "thongke_Vungdich","KhaiBaoAdmin") </td>
        <td>@Html.ActionLink("Details", "thongke_Trieuchung","KhaiBaoAdmin") </td>
    </tr>

</table>
<div class="row">

</div>

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/KhaiBaoAdmin/thongke_TiepXuc.cshtml
@using DACSN.Models
@using PagedList.Mvc;
@model PagedList.PagedList<DACSN.Models.ThongTin_KhaiBao>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<div>
    <p style="color:red; text-align:center; font-size:30px">
        THÔNG TIN NGƯỜI TIẾP XÚC NGƯỜI BỊ COVID
    </p>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().HoVaTen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NamSinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuocTich)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().PhuongXa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuanHuyen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhThanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhTrang)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.First().TiepXucCOVID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().NguoiVungCovid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().NguoiSotHo)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.First().NgayKhaiBao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoVaTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamSinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuocTich)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ward.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Province.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.TiepXucCOVID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiVungCovid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiSotHo)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.NgayKhaiBao)
            </td>

        </tr>
    }

</table>
<div>
    <!-- Thêm mã phân trang -->
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    <div class="MenuTrang">

        @Html.PagedListPager(Model, page => Url.Action("thongke_TiepXuc", new { page = page }))
    </div>
    <style>
        .MenuTrang {
            display: inline;
            text-align: center;
        }
    </style>
</div>
        @Html.ActionLink("Quay lại Trang", "ThongKe", "KhaiBaoAdmin")

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/KhaiBaoAdmin/thongke_Trieuchung.cshtml
@using DACSN.Models
@using PagedList.Mvc;
@model PagedList.PagedList<DACSN.Models.ThongTin_KhaiBao>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<div>
    <p style="color:red; text-align:center; font-size:30px">
        THÔNG TIN NGƯỜI TIẾP XÚC NGƯỜI CÓ TRIỆU CHỨNG 
    </p>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().HoVaTen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CMND)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NamSinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().GioiTinh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuocTich)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DiaChi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().PhuongXa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().QuanHuyen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhThanh)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().DienThoai)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().TinhTrang)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.First().TiepXucCOVID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().NguoiVungCovid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().NguoiSotHo)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.First().NgayKhaiBao)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoVaTen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NamSinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioiTinh)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuocTich)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ward.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.District.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Province.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TinhTrang)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.TiepXucCOVID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiVungCovid)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NguoiSotHo)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.NgayKhaiBao)
            </td>

        </tr>
    }

</table>
<div>
    <!-- Thêm mã phân trang -->
    Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
    <div class="MenuTrang">

        @Html.PagedListPager(Model, page => Url.Action("thongke_Trieuchung", new { page = page }))
    </div>
    <style>
        .MenuTrang {
            display: inline;
            text-align: center;
        }
    </style>
</div>
@Html.ActionLink("Quay lại Trang", "ThongKe", "KhaiBaoAdmin")