DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Controllers/BaiVietController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DACSN.Models;
using System.IO;
using PagedList;

namespace DACSN.Areas.Admin.Controllers
{
    public class BaiVietController : Controller
    {
        dbDuLieuYTeBDDataContext db = new dbDuLieuYTeBDDataContext();
        // GET: Admin/BaiViet
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 5;
            return View(db.BaiViets.ToList().OrderBy(n => n.IdBV).ToPagedList(iPageNum, iPageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.IdDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(BaiViet bv, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            //đưa dữ liệu vào DropDown
            ViewBag.MaDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM");

            if (fFileUpload == null)
            {
                // nội dung thông báo yêu cầu chọn ảnh bìa
                ViewBag.ThongBao = "Hãy chọn ảnh bìa.";
                //lưu thông tin để khi load lại trang do yêu cầu
                // chọn ảnh bìa sẽ hiển thị các thông tin này lên trang
                ViewBag.TieuDe = f["sTieuDe"];
                ViewBag.TomTat = f["sTomTat"];
                ViewBag.NoiDung = f["sNoiDung"];
                ViewBag.LinkVideo = f["sLinkVideo"];
                ViewBag.NguoiViet = f["sNguoiViet"];
                ViewBag.MaDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM", f["MaDM"]);
                ViewBag.Tag = f["sTag"];
                return View();

            }
            else
            {
                if (ModelState.IsValid)
                {
                    // lấy tên file (khai báo thư viện :System.Io
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    // lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    // kiểm tra ảnh bìa đã tồn tại chưa để lưu lên thư mục
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    // lưu Sách vào csdl
                    bv.TieuDe = f["sTieuDe"];
                    bv.TomTat = f["sTomTat"];
                    bv.NoiDung = f["sNoiDung"];
                    bv.Hinh = sFileName;
                    bv.NguoiViet = f["sNguoiViet"];
                    bv.NgayViet = DateTime.Now;
                    bv.Tag = f["sTag"];
                    bv.LinkVideo = f["sLinkVideo"];
                    bv.NguoiViet = f["sNguoiViet"];
                    bv.IdDM = int.Parse(f["IdDM"]);
                    db.BaiViets.InsertOnSubmit(bv);
                    db.SubmitChanges();
                    // về lại trang quản lý sản phẩm
                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);
            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(bv);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);
            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(bv);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int? id, FormCollection f)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);

            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            
            db.BaiViets.DeleteOnSubmit(bv);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);
            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.IdDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM");
            return View(bv);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == int.Parse(f["iIdBV"]));
            ViewBag.MaDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM", f["MaDM"]);
            if (ModelState.IsValid)
            {
                if (fFileUpload != null) //Kiểm tra để xác nhận cho thay đổi ảnh bìa
                {
                    //Lấy tên file (Khai báo thư viện: System.IO)
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    //Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    //Kiểm tra file đã tồn tại chưa
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    bv.Hinh = sFileName;
                }
                //Lưu Sach vào CSDL
                bv.TieuDe = f["sTieuDe"];
                bv.TomTat = f["sTomTat"];
                bv.NoiDung = f["sNoiDung"];
                bv.NgayViet = DateTime.Now;
                bv.NguoiViet = f["sNguoiViet"];
                bv.LinkVideo = f["sLinkVideo"];
                bv.Tag = f["sTag"];
                bv.IdDM = int.Parse(f["IdDM"]);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(bv);
        }
    }
}

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Controllers/BaiVietNVController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DACSN.Models;
using System.IO;
using PagedList;

namespace DACSN.Areas.Admin.Controllers
{
    public class BaiVietNVController : Controller
    {
        dbDuLieuYTeBDDataContext db = new dbDuLieuYTeBDDataContext();
        // GET: Admin/BaiVietNV
       
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 5;
            return View(db.BaiViets.ToList().OrderBy(n => n.IdBV).ToPagedList(iPageNum, iPageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.IdDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(BaiViet bv, FormCollection f, HttpPostedFileBase fFileUpload)
        {
            //đưa dữ liệu vào DropDown
            ViewBag.MaDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM");

            if (fFileUpload == null)
            {
                // nội dung thông báo yêu cầu chọn ảnh bìa
                ViewBag.ThongBao = "Hãy chọn ảnh bìa.";
                //lưu thông tin để khi load lại trang do yêu cầu
                // chọn ảnh bìa sẽ hiển thị các thông tin này lên trang
                ViewBag.TieuDe = f["sTieuDe"];
                ViewBag.TomTat = f["sTomTat"];
                ViewBag.NoiDung = f["sNoiDung"];
                ViewBag.LinkVideo = f["sLinkVideo"];
                ViewBag.NguoiViet = f["sNguoiViet"];
                ViewBag.MaDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM", f["MaDM"]);
                ViewBag.Tag = f["sTag"];
                return View();

            }
            else
            {
                if (ModelState.IsValid)
                {
                    // lấy tên file (khai báo thư viện :System.Io
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    // lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    // kiểm tra ảnh bìa đã tồn tại chưa để lưu lên thư mục
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    // lưu Sách vào csdl
                    bv.TieuDe = f["sTieuDe"];
                    bv.TomTat = f["sTomTat"];
                    bv.NoiDung = f["sNoiDung"];
                    bv.Hinh = sFileName;
                    bv.NguoiViet = f["sNguoiViet"];
                    bv.NgayViet = DateTime.Now;
                    bv.Tag = f["sTag"];
                    bv.LinkVideo = f["sLinkVideo"];
                    bv.NguoiViet = f["sNguoiViet"];
                    bv.IdDM = int.Parse(f["IdDM"]);
                    db.BaiViets.InsertOnSubmit(bv);
                    db.SubmitChanges();
                    // về lại trang quản lý sản phẩm
                    return RedirectToAction("Index");
                }
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);
            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(bv);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);
            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(bv);
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int? id, FormCollection f)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);

            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }

            db.BaiViets.DeleteOnSubmit(bv);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == id);
            if (bv == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            ViewBag.IdDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM");
            return View(bv);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection f, HttpPostedFileBase fFileUpload)
        {
            var bv = db.BaiViets.SingleOrDefault(n => n.IdBV == int.Parse(f["iIdBV"]));
            ViewBag.MaDM = new SelectList(db.DanhMucs.ToList().OrderBy(n => n.TenDM), "IdDM", "TenDM", f["MaDM"]);
            if (ModelState.IsValid)
            {
                if (fFileUpload != null) //Kiểm tra để xác nhận cho thay đổi ảnh bìa
                {
                    //Lấy tên file (Khai báo thư viện: System.IO)
                    var sFileName = Path.GetFileName(fFileUpload.FileName);
                    //Lấy đường dẫn lưu file
                    var path = Path.Combine(Server.MapPath("~/Images"), sFileName);
                    //Kiểm tra file đã tồn tại chưa
                    if (!System.IO.File.Exists(path))
                    {
                        fFileUpload.SaveAs(path);
                    }
                    bv.Hinh = sFileName;
                }
                //Lưu Sach vào CSDL
                bv.TieuDe = f["sTieuDe"];
                bv.TomTat = f["sTomTat"];
                bv.NoiDung = f["sNoiDung"];
                bv.NgayViet = DateTime.Now;
                bv.NguoiViet = f["sNguoiViet"];
                bv.LinkVideo = f["sLinkVideo"];
                bv.Tag = f["sTag"];
                bv.IdDM = int.Parse(f["IdDM"]);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(bv);
        }
    }
}

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Controllers/DanhMucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DACSN.Models;
using System.IO;
using PagedList;

namespace DACSN.Areas.Admin.Controllers
{
    public class DanhMucController : Controller
    {
        dbDuLieuYTeBDDataContext db = new dbDuLieuYTeBDDataContext();
        // GET: Admin/DanhMuc
        public ActionResult Index(int? page)
        {
            int iPageNum = (page ?? 1);
            int iPageSize = 5;
            return View(db.DanhMucs.ToList().OrderBy(n => n.IdDM).ToPagedList(iPageNum, iPageSize));
        }

        public DanhMuc GetDM(int id)
        {
            return db.DanhMucs.Where(dm => dm.IdDM == id).SingleOrDefault();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            DanhMuc dm = db.DanhMucs.Where(n => n.IdDM == id).SingleOrDefault();
            return View(dm);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit()
        {
            if (ModelState.IsValid)
            {
                var dm = GetDM(int.Parse(Request.Form["IdDM"]));
                dm.TenDM = Request.Form["TenDM"];
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit");
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(FormCollection f)
        {
            if (ModelState.IsValid)
            {
                DanhMuc dm = new DanhMuc();

                dm.TenDM = f["TenDM"];
                db.DanhMucs.InsertOnSubmit(dm);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Delete");
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {

            return View(GetDM(id));
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection f)
        {
            var dm = GetDM(id);
            if (dm == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.DanhMucs.InsertOnSubmit(dm);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hệ Thống Quản Lý Của Nhân Viên</title>
    <link rel="SHORTCUT ICON" href="~/Images/LogoBD.ico">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/ThongBao.js"></script>
    <style type="text/css">
        body, html {
            font-family: 'Source Sans Pro', sans-serif;
            background-color: #1d243d;
            padding: 0;
            margin: 0;
        }

        .container {
            margin: 0;
            top: 50px;
            left: 50%;
            position: absolute;
            text-align: center;
            transform: translateX(-50%);
            background-color: rgb( 33, 41, 66 );
            border-radius: 9px;
            border-top: 10px solid #79a6fe;
            border-bottom: 10px solid #8BD17C;
            width: 400px;
            height: auto;
            box-shadow: 1px 1px 108.8px 19.2px rgb(25 31 53);
        }

        }

        /* .col-md-offset-2 {
            margin-left: 7.666667%;
        }*/

        .col-md-10 {
            width: 77.333333%;
        }


        .TieuDe h4 {
            text-align: center;
            font-weight: bold;
            font-family: 'Source Sans Pro', sans-serif;
            color: #5c6bc0;
            font-size: 18px;
            /*margin-top: 94px;*/
        }

        .TieuDe span {
            color: #dfdeee;
            font-weight: lighter;
        }

        .TieuDe h5 {
            text-align: center;
            font-style: inherit;
            font-family: 'Source Sans Pro', sans-serif;
            font-size: 13px;
            color: #a1a4ad;
            letter-spacing: 1.5px;
            /* margin-top: -15px;*/
            /*  margin-bottom: 70px;*/
        }

        .TieuDe h2 {
            text-align: center;
            font-weight: bold;
            font-family: 'Source Sans Pro', sans-serif;
            color: #5c6bc0;
            font-size: 18px;
        }

        .body-content {
            left: 50%;
        }

        .QuayVe {
            background: #456BD9;
            border: 0.1875em solid #0F1C3F;
            border-radius: 50%;
            box-shadow: 0.375em 0.375em 0 0 rgba(15, 28, 63, 0.125);
            height: 3em;
            width: 3em;
            right: 50%;
        }
    </style>
</head>
<body>

    <div class="container body-content">
        <button class="QuayVe"></button>

        @if (TempData["AlertMessage"] != null)
        {
    <div id="AlertBox" class="alert @TempData["AlertType"] hide" role="alert">
        @TempData["AlertMessage"]
    </div>}

        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

DoAnCoSoNganh_NhomF1/DACSN/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="SHORTCUT ICON" href="~/Images/LogoBD.ico">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="~/Plugin/AdminTemplate/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Plugin/AdminTemplate/fonts/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Plugin/AdminTemplate/css/animate.min.css" rel="stylesheet" />
    <!-- Custom styling plus plugins -->

    <link href="~/Plugin/AdminTemplate/css/custom.css" rel="stylesheet" />
    <link href="~/Plugin/AdminTemplate/css/maps/jquery-jvectormap-2.0.1.css" rel="stylesheet" />
    <link href="~/Plugin/AdminTemplate/css/icheck/flat/green.css" rel="stylesheet" />
    <link href="~/Plugin/AdminTemplate/css/floatexamples.css" rel="stylesheet" />
    <script src="~/Plugin/AdminTemplate/js/jquery.min.js"></script>
    <script src="~/Plugin/AdminTemplate/js/nprogress.js"></script>
    <script>
        NProgress.start();
    </script>

    <script src="~/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: 'textarea',
            plugins: [
                'advlist autolink link image lists charmap print preview hr anchor pagebreak',
                'searchreplace wordcount visualblocks code fullscreen insertdatetime media nonbreaking',
                'table emoticons template paste help',
            ],
            toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
                'bullist numlist outdent indent | link image | print preview media fullscreen | ' +
                'forecolor backcolor emoticons | help',
            menu: {
                favs: { title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons' }
            },
            menubar: 'favs file edit view insert format tools table help',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
        });


    </script>
    <!--[if lt IE 9]>
        <script src="../assets/js/ie8-responsive-file-warning.js"></script>
        <![endif]-->
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>

<body class="nav-md">
    <div class="container body">

        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="" id="linkHomePage" class="site_title"><i class="fa fa-paw"></i> <span>Admin Page</span></a>
                        <script>
                            window.document.getElementById('linkHomePage').href = window.location.origin;
                        </script>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu prile quick info -->
                    <div class="profile">
                        <div class="profile_pic">
                            <img src='~/Images/ys.jpg' class="img-circle profile_img" />
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>Hà Quốc Phong</h2>
                        </div>
                    </div>
                    <!-- /menu prile quick info -->
                    <br />

                    <!-- sidebar menu -->
                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-home"></i> Quản lý tài khoản <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>
                                            <a href="#">Danh sách tài khoản</a>
                                        </li>
                                        <li>
                                            <a href="#">Thêm tài khoản</a>
                                        </li>
                                        <li>
                                            <a href="#">Thông tin cá nhân</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a><i class="fa fa-bar-chart-o"></i> Thống Kê <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>
                                            @*<a href="#">Biểu đồ thống kê</a>*@
                                            @Html.ActionLink("Biểu đồ thống kê", "ThongKe", "KhaiBaoAdmin")
                                        </li>
                                        <li>
                                            <a href="#">Lượng truy cập</a>
                                        </li>
                                        <li>
                                            <a href="#">Lượt đăng ký thành viên</a>
                                        </li>
                                        <li>
                                            <a href="#">Lương bài post</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="menu_section">
                            <h3>Phần Danh Mục</h3>
                            <ul class="nav side-menu">
                                <li>
                                    <a><i class="fa fa-windows"></i> Quản lý bài viết<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu" style="display: none">
                                        <li>
                                            @Html.ActionLink("Tạo bài viết", "Create", "BaiViet")
                                        </li>
                                        <li>
                                            <a href="#">Duyệt bài</a>
                                        </li>
                                        <li>
                                            @Html.ActionLink("Danh sách bài viết", "Index", "BaiViet")
                                        </li>
                                        <li>
                                            @Html.ActionLink("Danh sách danh mục", "Index", "DanhMuc")
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    @*<a href="~/KhaiBao/KhaiBaoYTe"><i class="fa fa-laptop"></i>Quản lý khai báo y tế</a>*@
                                   @Html.ActionLink("Quản lý khai báo y tế","KhaiBaoYTe","KhaiBaoAdmin")
                                </li>
                                <li>
                                    <a><i class="fa fa-border" ></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /sidebar menu -->

                </div>
            </div>
            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">
                    <nav class="" role="navigation">
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                            <li class="">
                                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                    <!--<img src='~/Images/Members/@Session["temp"]/@Session["image"]' class="img-circle profile_img" />-->
                                    <img src='~/Images/ys.jpg' class="img-circle profile_img" />
                                </a>
                                <ul class="dropdown-menu dropdown-usermenu animated fadeInDown pull-right">
                                    <li>
                                        <a href="#"> Thông tin cá nhân</a>
                                    </li>
                                    <li>
                                        <a href="#">Trợ giúp</a>
                                    </li>
                                    <li>
                                        @Html.ActionLink("Đăng xuất","DangXuat","Admin")
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                @RenderBody()

            </div>
            <!-- /page content -->
        </div>
    </div>
    <div id="custom_notifications" class="custom-notifications dsp_none">
        <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group"></ul>
        <div class="clearfix"></div>
        <div id="notif-group" class="tabbed_notifications"></div>
    </div>

    <script src="~/Plugin/AdminTemplate/js/bootstrap.min.js"></script>
    <!-- gauge js -->
    <script src="~/Plugin/AdminTemplate/js/gauge/gauge.min.js"></script>
    <script src="~/Plugin/AdminTemplate/js/gauge/gauge_demo.js"></script>
    <!-- chart js -->
    <script src="~/Plugin/AdminTemplate/js/chartjs/chart.min.js"></script>
    <!-- bootstrap progress js -->
    <script src="~/Plugin/AdminTemplate/js/progressbar/bootstrap-progressbar.min.js"></script>
    <script src="~/Plugin/AdminTemplate/js/nicescroll/jquery.nicescroll.min.js"></script>
    <!-- icheck -->

    <script src="~/Plugin/AdminTemplate/js/icheck/icheck.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/Plugin/AdminTemplate/js/moment.min.js"></script>
    <script src="~/Plugin/AdminTemplate/js/datepicker/daterangepicker.js"></script>

    <script src="~/Plugin/AdminTemplate/js/custom.js"></script>
    <!-- flot js -->
    <!--[if lte IE 8]><script type="text/javascript" src="js/excanvas.min.js"></script><![endif]-->

    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.pie.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.orderBars.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.time.min.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/date.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.spline.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.stack.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/curvedLines.js"></script>
    <script src="~/Plugin/AdminTemplate/js/flot/jquery.flot.resize.js"></script>

   
    <!-- /datepicker -->
    <!-- /footer content -->
</body>
</html>